site_name: UR Polyscope 5 Robots Vision Manual
site_description: Example UR (E-series, Polyscope 5) URCap integration for the wenglor robot vision API.
site_url: https://wenglor.github.io/robot-vision-ur-polyscope5/
repo_url: https://github.com/wenglor/robot-vision-ur-polyscope5
repo_name: robot-vision-ur-polyscope5
use_directory_urls: true

theme:
  name: material
  logo: images/wenglor_logo.svg
  features:
    - navigation.indexes
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.tabs.link
    - toc.integrate
    - search.highlight
    - search.suggest

nav:
  - index.md
  - 1. Installation of URCap:
    - 1_0_installation/index.md
  - 2. User Configuration:
    - 2_0_user_configuration/index.md
  - 3. Robot Program:
    - 3_0_robot_program/index.md
  - 4. Troubleshooting:
    - 4_0_troubleshooting/index.md
  - 5. Support & Feedback:
    - 5_0_support_and_feedback/index.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.snippets

docs_dir: docs

extra:
  generator: false

copyright: "© 2026 wenglor sensoric group"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - path: javascripts/mermaid.mjs
    type: module

extra_css:
  - css/image_format.css
  - css/wenglor.css
